language: ruby
cache: bundler
rvm:
- 2.4.1
sudo: false
env:
  - AWS_REGION: us-west-2
deploy:
  provider: rubygems
  gem:
    master: elbas
  on:
    repo: lserman/capistrano-elbas
    branch: master
  api_key:
    secure: gRiZBVBq+/AtMoOeSsMlnCLawQVzN/SVXyOC7+5gni8iKPGDpXL+CBrUv410WStBmA2c4SYn9lNmeLOea31TOA0yIMnjfjA36jPNKzKWThRb9NuUzV8ySGqBcqp1YhvZta46Jv+d3HovGgSJ0aw5tCSfB+gPdwNvkFvqe+zIy3Y=
